<a href="https://colab.research.google.com/github/ohhhanna/PYTORCH_j/blob/main/tensor_intro1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#TENSOR
#a torch.Tensor is a multidimsional matrix
#similar to numpy arrays but works beter in GPU
#default type is float
#we can cange the type later

In [2]:
import torch
import numpy as np

LISTS

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,0]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

numpy arrays

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.42850678, 0.62568863, 0.21947796, 0.18594269],
       [0.24461667, 0.74908218, 0.68642966, 0.40980084],
       [0.58123927, 0.93926701, 0.47762464, 0.80678671]])

In [5]:
np1.dtype

dtype('float64')

TENSORS

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.8559, -0.7461, -0.7970, -1.2725],
        [ 0.6291, -0.6553, -0.9483,  0.8946],
        [-0.7244, -0.2493,  0.7729, -1.5586]])

tensor and numpy array act very similar, but tensor is sort of designed for deep learning and more powerful, we can go back and forth with these two

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
#create tensor out of numoy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4285, 0.6257, 0.2195, 0.1859],
        [0.2446, 0.7491, 0.6864, 0.4098],
        [0.5812, 0.9393, 0.4776, 0.8068]], dtype=torch.float64)