<a href="https://colab.research.google.com/github/ohhhanna/PYTORCH_j/blob/main/tensor_intro1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#TENSOR
#a torch.Tensor is a multidimsional matrix
#similar to numpy arrays but works beter in GPU
#default type is float
#we can cange the type later

In [2]:
import torch
import numpy as np

LISTS

In [3]:
my_list = [[1,2,3,4,5],[6,7,8,9,0]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 0]]

numpy arrays

In [4]:
np1 = np.random.rand(3,4)
np1

array([[0.42850678, 0.62568863, 0.21947796, 0.18594269],
       [0.24461667, 0.74908218, 0.68642966, 0.40980084],
       [0.58123927, 0.93926701, 0.47762464, 0.80678671]])

In [5]:
np1.dtype

dtype('float64')

TENSORS

In [6]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.8559, -0.7461, -0.7970, -1.2725],
        [ 0.6291, -0.6553, -0.9483,  0.8946],
        [-0.7244, -0.2493,  0.7729, -1.5586]])

tensor and numpy array act very similar, but tensor is sort of designed for deep learning and more powerful, we can go back and forth with these two

In [7]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
#create tensor out of numoy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.4285, 0.6257, 0.2195, 0.1859],
        [0.2446, 0.7491, 0.6864, 0.4098],
        [0.5812, 0.9393, 0.4776, 0.8068]], dtype=torch.float64)

tensor operations

In [9]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#how do we reshape and view
my_torch = my_torch.reshape(2,5)
my_torch
my_torch2 = my_torch.reshape(2,6)
my_torch2

RuntimeError: shape '[2, 6]' is invalid for input of size 10

In [17]:
#reshape if we dont know the number of items using -1
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
my_torch2 = my_torch2.reshape(3,-1)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [19]:
#view
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# While both functions offer ways to reshape tensors, torch. reshape may resort to copying data if non-contiguous memory layouts are encountered. In contrast, torch. view primarily focuses on creating views pointing to the original tensor's memory storage without duplicating data

In [21]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
#with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
my_torch5[1]=4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [27]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [28]:
#slices allow you to grab a section of the tensor
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#grabe a specific item
my_torch7[7]

tensor(7)

In [31]:
#grab a slice
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [33]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [34]:
#return a columm
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])