<a href="https://colab.research.google.com/github/ohhhanna/PYTORCH_j/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tensor math operations
addition sub multiply
shorthand longhand
reassignment

In [1]:
import torch
import numpy as np

In [24]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
#addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
#subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [5]:
#addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:
#subtraction
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [8]:
#multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [12]:
#division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [14]:
#remainders
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [16]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [18]:
#exponents
tensor_a ** tensor_b
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [19]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [25]:
#reassigmnet "_"
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [26]:
tensor_a

tensor([ 6,  8, 10, 12])

In [27]:
torch.add_(tensor_a,tensor_b)

AttributeError: module 'torch' has no attribute 'add_'